ARG BOOST_VERSION="1.89.0"
ARG BOOST_VARIANT="release"
ARG LINK="shared"

FROM ghcr.io/zen0x7/compiler:${BOOST_VERSION}-${LINK}-${BOOST_VARIANT}

ARG BOOST_VARIANT
ARG LINK
ARG BOOST_VERSION="1.89.0"

WORKDIR /srv/engine

RUN echo $LINK;
RUN echo $BOOST_VARIANT;
RUN echo $BOOST_VERSION;

COPY . .
RUN sh scripts/build.sh ${BOOST_VARIANT} ${LINK}