ARG BOOST_VERSION="1.89.0"
ARG BOOST_VARIANT="release"
ARG LINK="shared"

FROM ghcr.io/zen0x7/compiler:${BOOST_VERSION}-${BOOST_VARIANT}-${LINK}

ARG BOOST_VARIANT
ARG LINK
ARG BOOST_VERSION="1.89.0"

WORKDIR /srv

COPY . .
RUN sh scripts/build.sh ${BOOST_VARIANT} ${LINK}

EXPOSE 9000
ENTRYPOINT ["/srv/build/server"]